/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const BannerFileMetadata = IDL.Record({
  'id' : IDL.Nat,
  'isAnimated' : IDL.Bool,
  'file' : ExternalBlob,
});
export const BannerImageSource = IDL.Variant({
  'url' : IDL.Text,
  'file' : BannerFileMetadata,
});
export const BannerImage = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'timestamp' : IDL.Int,
  'image' : BannerImageSource,
});
export const SliderImageSource = IDL.Variant({
  'url' : IDL.Text,
  'file' : BannerFileMetadata,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AdminPermission = IDL.Variant({
  'ManageResources' : IDL.Null,
  'ManageAlumni' : IDL.Null,
  'ManageSlider' : IDL.Null,
  'ManageCitizenCharter' : IDL.Null,
  'ManageHeritage' : IDL.Null,
  'ManageHymn' : IDL.Null,
  'ManageBanners' : IDL.Null,
  'ManageFooter' : IDL.Null,
  'ManageClubs' : IDL.Null,
});
export const AdminUserData = IDL.Record({
  'permissions' : IDL.Vec(AdminPermission),
  'principal' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'isActive' : IDL.Bool,
  'email' : IDL.Text,
  'lastLogin' : IDL.Opt(IDL.Int),
});
export const AlumniProfile = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'graduationYear' : IDL.Text,
  'achievements' : IDL.Text,
  'currentPosition' : IDL.Text,
});
export const ContactInfoSection = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'createdAt' : IDL.Int,
  'isActive' : IDL.Bool,
  'updatedAt' : IDL.Int,
});
export const OfficeHoursSection = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'createdAt' : IDL.Int,
  'isActive' : IDL.Bool,
  'updatedAt' : IDL.Int,
});
export const ResourceSubcategory = IDL.Record({
  'url' : IDL.Text,
  'title' : IDL.Text,
  'isExternal' : IDL.Bool,
});
export const SchoolHoursSection = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'createdAt' : IDL.Int,
  'isActive' : IDL.Bool,
  'updatedAt' : IDL.Int,
});
export const SliderImage = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'displayOrder' : IDL.Nat,
  'description' : IDL.Text,
  'timestamp' : IDL.Int,
  'image' : SliderImageSource,
});
export const AlumniContent = IDL.Record({
  'title' : IDL.Text,
  'lastUpdated' : IDL.Int,
  'description' : IDL.Text,
  'communityEngagement' : IDL.Text,
});
export const BNHSHymnContent = IDL.Record({
  'video' : ExternalBlob,
  'lastUpdated' : IDL.Int,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
  'email' : IDL.Text,
});
export const CitizenCharterBackground = IDL.Record({
  'lastUpdated' : IDL.Int,
  'isActive' : IDL.Bool,
  'backgroundImage' : IDL.Opt(ExternalBlob),
});
export const CitizenCharterContactInfo = IDL.Record({
  'title' : IDL.Text,
  'contactInfo' : IDL.Text,
  'officeHours' : IDL.Text,
  'lastUpdated' : IDL.Int,
  'schoolAddress' : IDL.Text,
  'schoolHours' : IDL.Text,
});
export const CitizenCharterStaticImage = IDL.Record({
  'lastUpdated' : IDL.Int,
  'staticImage' : IDL.Opt(ExternalBlob),
});
export const ClubOrganization = IDL.Record({
  'id' : IDL.Nat,
  'members' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'activities' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
});
export const DepEdMissionContent = IDL.Record({
  'mission' : IDL.Text,
  'lastUpdated' : IDL.Int,
  'version' : IDL.Nat,
});
export const DepEdVisionContent = IDL.Record({
  'mission' : IDL.Text,
  'coreValues' : IDL.Text,
  'lastUpdated' : IDL.Int,
  'version' : IDL.Nat,
  'bnhsStatisticalBulletinTitle' : IDL.Text,
  'mandates' : IDL.Text,
  'vision' : IDL.Text,
});
export const FileTypeBreakdown = IDL.Record({
  'documents' : IDL.Nat,
  'videos' : IDL.Nat,
  'images' : IDL.Nat,
});
export const FooterContactInfo = IDL.Record({
  'lastUpdated' : IDL.Int,
  'email' : IDL.Text,
  'schoolAddress' : IDL.Text,
  'phone' : IDL.Text,
});
export const FooterSocialMedia = IDL.Record({
  'lastUpdated' : IDL.Int,
  'facebookUrl' : IDL.Text,
});
export const FontStyle = IDL.Variant({
  'italic' : IDL.Null,
  'normal' : IDL.Null,
  'bold' : IDL.Null,
  'underline' : IDL.Null,
});
export const TextAlignment = IDL.Variant({
  'center' : IDL.Null,
  'left' : IDL.Null,
  'justify' : IDL.Null,
  'right' : IDL.Null,
});
export const FormattedText = IDL.Record({
  'content' : IDL.Text,
  'fontStyle' : FontStyle,
  'fontSize' : IDL.Nat16,
  'alignment' : TextAlignment,
});
export const HeritageSectionContent = IDL.Record({
  'title' : IDL.Text,
  'lastUpdated' : IDL.Int,
  'formattedText' : FormattedText,
  'backgroundImage' : IDL.Opt(ExternalBlob),
  'orgChartBackground' : IDL.Opt(ExternalBlob),
});
export const AnalyticsPeriod = IDL.Record({
  'monthly' : IDL.Nat,
  'yearly' : IDL.Nat,
  'daily' : IDL.Nat,
  'weekly' : IDL.Nat,
});
export const OrganizationalStructureContent = IDL.Record({
  'lastUpdated' : IDL.Int,
  'titleBackground' : IDL.Opt(ExternalBlob),
  'staticImage' : IDL.Opt(ExternalBlob),
});
export const LoginRecord = IDL.Record({
  'principal' : IDL.Principal,
  'role' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const StorageStats = IDL.Record({
  'fileCount' : IDL.Nat,
  'lastUpdated' : IDL.Int,
  'usedSpace' : IDL.Nat,
  'availableSpace' : IDL.Nat,
  'totalCapacity' : IDL.Nat,
});
export const Header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'activateBanner' : IDL.Func([IDL.Nat], [], []),
  'addBannerImage' : IDL.Func(
      [BannerImageSource, IDL.Text, IDL.Text],
      [BannerImage],
      [],
    ),
  'addSliderImage' : IDL.Func(
      [SliderImageSource, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAdminUser' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Text, IDL.Vec(AdminPermission)],
      [],
      [],
    ),
  'createAlumniProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'createClubOrganization' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Vec(IDL.Text)],
      [],
      [],
    ),
  'createContactInfoSection' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'createOfficeHoursSection' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'createSchoolHoursSection' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'deactivateBanner' : IDL.Func([IDL.Nat], [], []),
  'deleteAdminUser' : IDL.Func([IDL.Principal], [], []),
  'deleteAlumniProfile' : IDL.Func([IDL.Nat], [], []),
  'deleteBanner' : IDL.Func([IDL.Nat], [], []),
  'deleteClubOrganization' : IDL.Func([IDL.Nat], [], []),
  'deleteContactInfoSection' : IDL.Func([IDL.Nat], [], []),
  'deleteOfficeHoursSection' : IDL.Func([IDL.Nat], [], []),
  'deleteSchoolHoursSection' : IDL.Func([IDL.Nat], [], []),
  'deleteSliderImage' : IDL.Func([IDL.Nat], [], []),
  'getActiveBanners' : IDL.Func([], [IDL.Vec(BannerImage)], ['query']),
  'getAdminUser' : IDL.Func([IDL.Principal], [AdminUserData], ['query']),
  'getAllAdminUsers' : IDL.Func([], [IDL.Vec(AdminUserData)], ['query']),
  'getAllAlumniProfiles' : IDL.Func([], [IDL.Vec(AlumniProfile)], ['query']),
  'getAllBanners' : IDL.Func([], [IDL.Vec(BannerImage)], ['query']),
  'getAllContactInfoSections' : IDL.Func(
      [],
      [IDL.Vec(ContactInfoSection)],
      ['query'],
    ),
  'getAllOfficeHoursSections' : IDL.Func(
      [],
      [IDL.Vec(OfficeHoursSection)],
      ['query'],
    ),
  'getAllResourceSubcategories' : IDL.Func(
      [],
      [IDL.Vec(ResourceSubcategory)],
      ['query'],
    ),
  'getAllSchoolHoursSections' : IDL.Func(
      [],
      [IDL.Vec(SchoolHoursSection)],
      ['query'],
    ),
  'getAllSliderImages' : IDL.Func([], [IDL.Vec(SliderImage)], ['query']),
  'getAlumniContent' : IDL.Func([], [AlumniContent], ['query']),
  'getAlumniProfile' : IDL.Func([IDL.Nat], [AlumniProfile], ['query']),
  'getBNHSHymnMetadata' : IDL.Func([], [BNHSHymnContent], ['query']),
  'getBNHSHymnVideo' : IDL.Func([], [ExternalBlob], ['query']),
  'getBannerById' : IDL.Func([IDL.Nat], [BannerImage], ['query']),
  'getBannerVersion' : IDL.Func([], [IDL.Nat], ['query']),
  'getCallerPermissions' : IDL.Func([], [IDL.Vec(AdminPermission)], ['query']),
  'getCallerRole' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCitizenCharterBackground' : IDL.Func(
      [],
      [CitizenCharterBackground],
      ['query'],
    ),
  'getCitizenCharterBackgroundImage' : IDL.Func(
      [IDL.Int],
      [IDL.Opt(ExternalBlob)],
      ['query'],
    ),
  'getCitizenCharterBackgroundImageById' : IDL.Func(
      [IDL.Int],
      [ExternalBlob],
      ['query'],
    ),
  'getCitizenCharterContactInfo' : IDL.Func(
      [],
      [CitizenCharterContactInfo],
      ['query'],
    ),
  'getCitizenCharterStaticImage' : IDL.Func(
      [],
      [CitizenCharterStaticImage],
      ['query'],
    ),
  'getCitizenCharterStaticImageById' : IDL.Func(
      [IDL.Int],
      [ExternalBlob],
      ['query'],
    ),
  'getCitizenCharterStaticImageByTimestamp' : IDL.Func(
      [IDL.Int],
      [IDL.Opt(ExternalBlob)],
      ['query'],
    ),
  'getClubOrganization' : IDL.Func([IDL.Nat], [ClubOrganization], ['query']),
  'getClubOrganizations' : IDL.Func([], [IDL.Vec(ClubOrganization)], ['query']),
  'getContactInfoSection' : IDL.Func(
      [IDL.Nat],
      [ContactInfoSection],
      ['query'],
    ),
  'getCurrentBanner' : IDL.Func([], [BannerImage], ['query']),
  'getDepEdMission' : IDL.Func([], [DepEdMissionContent], ['query']),
  'getDepEdVision' : IDL.Func([], [DepEdVisionContent], ['query']),
  'getFileTypeBreakdown' : IDL.Func([], [FileTypeBreakdown], ['query']),
  'getFooterContactInfo' : IDL.Func([], [FooterContactInfo], ['query']),
  'getFooterSocialMedia' : IDL.Func([], [FooterSocialMedia], ['query']),
  'getHeritageSection' : IDL.Func([], [HeritageSectionContent], ['query']),
  'getHistoryBackgroundImage' : IDL.Func(
      [IDL.Int],
      [IDL.Opt(ExternalBlob)],
      ['query'],
    ),
  'getHistoryBackgroundImageById' : IDL.Func(
      [IDL.Int],
      [ExternalBlob],
      ['query'],
    ),
  'getLastActiveBanner' : IDL.Func([], [BannerImage], ['query']),
  'getLoginAnalytics' : IDL.Func([], [AnalyticsPeriod], ['query']),
  'getOfficeHoursSection' : IDL.Func(
      [IDL.Nat],
      [OfficeHoursSection],
      ['query'],
    ),
  'getOrganizationalStructure' : IDL.Func(
      [],
      [OrganizationalStructureContent],
      ['query'],
    ),
  'getRecentLoginRecords' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(LoginRecord)],
      ['query'],
    ),
  'getResourceSubcategory' : IDL.Func(
      [IDL.Text],
      [ResourceSubcategory],
      ['query'],
    ),
  'getSchoolHoursSection' : IDL.Func(
      [IDL.Nat],
      [SchoolHoursSection],
      ['query'],
    ),
  'getSliderImage' : IDL.Func([IDL.Nat], [SliderImage], ['query']),
  'getStorageStats' : IDL.Func([], [StorageStats], ['query']),
  'getTotalVisitors' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVisitorAnalytics' : IDL.Func([], [AnalyticsPeriod], ['query']),
  'initializeResources' : IDL.Func([], [], []),
  'initializeSuperAdmin' : IDL.Func([], [IDL.Principal], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'proxyPublicImage' : IDL.Func([IDL.Text, IDL.Vec(Header)], [IDL.Text], []),
  'recordLogin' : IDL.Func([], [], []),
  'recordVisitor' : IDL.Func([IDL.Text], [], []),
  'recoverSuperAdmin' : IDL.Func([], [IDL.Text], []),
  'removeBNHSHymn' : IDL.Func([], [], []),
  'removeCitizenCharterBackgroundImage' : IDL.Func([], [], []),
  'removeCitizenCharterStaticImage' : IDL.Func([], [], []),
  'removeHistoryBackgroundImage' : IDL.Func([], [], []),
  'removeOrganizationalChartBackground' : IDL.Func([], [], []),
  'removeOrganizationalStructureStaticImage' : IDL.Func([], [], []),
  'removeOrganizationalStructureTitleBackground' : IDL.Func([], [], []),
  'reorderSliderImages' : IDL.Func([IDL.Vec(IDL.Nat)], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setAdminUserStatus' : IDL.Func([IDL.Principal, IDL.Bool], [], []),
  'setBNHSHymn' : IDL.Func([ExternalBlob], [], []),
  'setCitizenCharterBackgroundImage' : IDL.Func([ExternalBlob], [], []),
  'setCitizenCharterStaticImage' : IDL.Func([ExternalBlob], [], []),
  'setHistoryBackgroundImage' : IDL.Func([ExternalBlob], [], []),
  'setOrganizationalChartBackground' : IDL.Func([ExternalBlob], [], []),
  'setOrganizationalStructureStaticImage' : IDL.Func([ExternalBlob], [], []),
  'setOrganizationalStructureTitleBackground' : IDL.Func(
      [ExternalBlob],
      [],
      [],
    ),
  'swapSliderImages' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateAdminUserPermissions' : IDL.Func(
      [IDL.Principal, IDL.Vec(AdminPermission)],
      [],
      [],
    ),
  'updateAlumniContent' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateAlumniProfile' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateBannerImage' : IDL.Func(
      [IDL.Nat, BannerImageSource, IDL.Text, IDL.Text],
      [BannerImage],
      [],
    ),
  'updateCitizenCharterContactInfo' : IDL.Func([], [], []),
  'updateClubOrganization' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Vec(IDL.Text)],
      [],
      [],
    ),
  'updateContactInfoSection' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateDepEdMission' : IDL.Func([IDL.Nat], [], []),
  'updateDepEdVision' : IDL.Func([IDL.Nat], [], []),
  'updateFooterContactInfo' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateFooterSocialMedia' : IDL.Func([IDL.Text], [], []),
  'updateHeritageSection' : IDL.Func([IDL.Text, FormattedText], [], []),
  'updateOfficeHoursSection' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateSchoolHoursSection' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateSliderImage' : IDL.Func(
      [IDL.Nat, SliderImageSource, IDL.Text, IDL.Text, IDL.Nat],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const BannerFileMetadata = IDL.Record({
    'id' : IDL.Nat,
    'isAnimated' : IDL.Bool,
    'file' : ExternalBlob,
  });
  const BannerImageSource = IDL.Variant({
    'url' : IDL.Text,
    'file' : BannerFileMetadata,
  });
  const BannerImage = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'timestamp' : IDL.Int,
    'image' : BannerImageSource,
  });
  const SliderImageSource = IDL.Variant({
    'url' : IDL.Text,
    'file' : BannerFileMetadata,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AdminPermission = IDL.Variant({
    'ManageResources' : IDL.Null,
    'ManageAlumni' : IDL.Null,
    'ManageSlider' : IDL.Null,
    'ManageCitizenCharter' : IDL.Null,
    'ManageHeritage' : IDL.Null,
    'ManageHymn' : IDL.Null,
    'ManageBanners' : IDL.Null,
    'ManageFooter' : IDL.Null,
    'ManageClubs' : IDL.Null,
  });
  const AdminUserData = IDL.Record({
    'permissions' : IDL.Vec(AdminPermission),
    'principal' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'isActive' : IDL.Bool,
    'email' : IDL.Text,
    'lastLogin' : IDL.Opt(IDL.Int),
  });
  const AlumniProfile = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'graduationYear' : IDL.Text,
    'achievements' : IDL.Text,
    'currentPosition' : IDL.Text,
  });
  const ContactInfoSection = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'createdAt' : IDL.Int,
    'isActive' : IDL.Bool,
    'updatedAt' : IDL.Int,
  });
  const OfficeHoursSection = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'createdAt' : IDL.Int,
    'isActive' : IDL.Bool,
    'updatedAt' : IDL.Int,
  });
  const ResourceSubcategory = IDL.Record({
    'url' : IDL.Text,
    'title' : IDL.Text,
    'isExternal' : IDL.Bool,
  });
  const SchoolHoursSection = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'createdAt' : IDL.Int,
    'isActive' : IDL.Bool,
    'updatedAt' : IDL.Int,
  });
  const SliderImage = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'displayOrder' : IDL.Nat,
    'description' : IDL.Text,
    'timestamp' : IDL.Int,
    'image' : SliderImageSource,
  });
  const AlumniContent = IDL.Record({
    'title' : IDL.Text,
    'lastUpdated' : IDL.Int,
    'description' : IDL.Text,
    'communityEngagement' : IDL.Text,
  });
  const BNHSHymnContent = IDL.Record({
    'video' : ExternalBlob,
    'lastUpdated' : IDL.Int,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Text,
    'email' : IDL.Text,
  });
  const CitizenCharterBackground = IDL.Record({
    'lastUpdated' : IDL.Int,
    'isActive' : IDL.Bool,
    'backgroundImage' : IDL.Opt(ExternalBlob),
  });
  const CitizenCharterContactInfo = IDL.Record({
    'title' : IDL.Text,
    'contactInfo' : IDL.Text,
    'officeHours' : IDL.Text,
    'lastUpdated' : IDL.Int,
    'schoolAddress' : IDL.Text,
    'schoolHours' : IDL.Text,
  });
  const CitizenCharterStaticImage = IDL.Record({
    'lastUpdated' : IDL.Int,
    'staticImage' : IDL.Opt(ExternalBlob),
  });
  const ClubOrganization = IDL.Record({
    'id' : IDL.Nat,
    'members' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'activities' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
  });
  const DepEdMissionContent = IDL.Record({
    'mission' : IDL.Text,
    'lastUpdated' : IDL.Int,
    'version' : IDL.Nat,
  });
  const DepEdVisionContent = IDL.Record({
    'mission' : IDL.Text,
    'coreValues' : IDL.Text,
    'lastUpdated' : IDL.Int,
    'version' : IDL.Nat,
    'bnhsStatisticalBulletinTitle' : IDL.Text,
    'mandates' : IDL.Text,
    'vision' : IDL.Text,
  });
  const FileTypeBreakdown = IDL.Record({
    'documents' : IDL.Nat,
    'videos' : IDL.Nat,
    'images' : IDL.Nat,
  });
  const FooterContactInfo = IDL.Record({
    'lastUpdated' : IDL.Int,
    'email' : IDL.Text,
    'schoolAddress' : IDL.Text,
    'phone' : IDL.Text,
  });
  const FooterSocialMedia = IDL.Record({
    'lastUpdated' : IDL.Int,
    'facebookUrl' : IDL.Text,
  });
  const FontStyle = IDL.Variant({
    'italic' : IDL.Null,
    'normal' : IDL.Null,
    'bold' : IDL.Null,
    'underline' : IDL.Null,
  });
  const TextAlignment = IDL.Variant({
    'center' : IDL.Null,
    'left' : IDL.Null,
    'justify' : IDL.Null,
    'right' : IDL.Null,
  });
  const FormattedText = IDL.Record({
    'content' : IDL.Text,
    'fontStyle' : FontStyle,
    'fontSize' : IDL.Nat16,
    'alignment' : TextAlignment,
  });
  const HeritageSectionContent = IDL.Record({
    'title' : IDL.Text,
    'lastUpdated' : IDL.Int,
    'formattedText' : FormattedText,
    'backgroundImage' : IDL.Opt(ExternalBlob),
    'orgChartBackground' : IDL.Opt(ExternalBlob),
  });
  const AnalyticsPeriod = IDL.Record({
    'monthly' : IDL.Nat,
    'yearly' : IDL.Nat,
    'daily' : IDL.Nat,
    'weekly' : IDL.Nat,
  });
  const OrganizationalStructureContent = IDL.Record({
    'lastUpdated' : IDL.Int,
    'titleBackground' : IDL.Opt(ExternalBlob),
    'staticImage' : IDL.Opt(ExternalBlob),
  });
  const LoginRecord = IDL.Record({
    'principal' : IDL.Principal,
    'role' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const StorageStats = IDL.Record({
    'fileCount' : IDL.Nat,
    'lastUpdated' : IDL.Int,
    'usedSpace' : IDL.Nat,
    'availableSpace' : IDL.Nat,
    'totalCapacity' : IDL.Nat,
  });
  const Header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'activateBanner' : IDL.Func([IDL.Nat], [], []),
    'addBannerImage' : IDL.Func(
        [BannerImageSource, IDL.Text, IDL.Text],
        [BannerImage],
        [],
      ),
    'addSliderImage' : IDL.Func(
        [SliderImageSource, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAdminUser' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Text, IDL.Vec(AdminPermission)],
        [],
        [],
      ),
    'createAlumniProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'createClubOrganization' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    'createContactInfoSection' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'createOfficeHoursSection' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'createSchoolHoursSection' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'deactivateBanner' : IDL.Func([IDL.Nat], [], []),
    'deleteAdminUser' : IDL.Func([IDL.Principal], [], []),
    'deleteAlumniProfile' : IDL.Func([IDL.Nat], [], []),
    'deleteBanner' : IDL.Func([IDL.Nat], [], []),
    'deleteClubOrganization' : IDL.Func([IDL.Nat], [], []),
    'deleteContactInfoSection' : IDL.Func([IDL.Nat], [], []),
    'deleteOfficeHoursSection' : IDL.Func([IDL.Nat], [], []),
    'deleteSchoolHoursSection' : IDL.Func([IDL.Nat], [], []),
    'deleteSliderImage' : IDL.Func([IDL.Nat], [], []),
    'getActiveBanners' : IDL.Func([], [IDL.Vec(BannerImage)], ['query']),
    'getAdminUser' : IDL.Func([IDL.Principal], [AdminUserData], ['query']),
    'getAllAdminUsers' : IDL.Func([], [IDL.Vec(AdminUserData)], ['query']),
    'getAllAlumniProfiles' : IDL.Func([], [IDL.Vec(AlumniProfile)], ['query']),
    'getAllBanners' : IDL.Func([], [IDL.Vec(BannerImage)], ['query']),
    'getAllContactInfoSections' : IDL.Func(
        [],
        [IDL.Vec(ContactInfoSection)],
        ['query'],
      ),
    'getAllOfficeHoursSections' : IDL.Func(
        [],
        [IDL.Vec(OfficeHoursSection)],
        ['query'],
      ),
    'getAllResourceSubcategories' : IDL.Func(
        [],
        [IDL.Vec(ResourceSubcategory)],
        ['query'],
      ),
    'getAllSchoolHoursSections' : IDL.Func(
        [],
        [IDL.Vec(SchoolHoursSection)],
        ['query'],
      ),
    'getAllSliderImages' : IDL.Func([], [IDL.Vec(SliderImage)], ['query']),
    'getAlumniContent' : IDL.Func([], [AlumniContent], ['query']),
    'getAlumniProfile' : IDL.Func([IDL.Nat], [AlumniProfile], ['query']),
    'getBNHSHymnMetadata' : IDL.Func([], [BNHSHymnContent], ['query']),
    'getBNHSHymnVideo' : IDL.Func([], [ExternalBlob], ['query']),
    'getBannerById' : IDL.Func([IDL.Nat], [BannerImage], ['query']),
    'getBannerVersion' : IDL.Func([], [IDL.Nat], ['query']),
    'getCallerPermissions' : IDL.Func(
        [],
        [IDL.Vec(AdminPermission)],
        ['query'],
      ),
    'getCallerRole' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCitizenCharterBackground' : IDL.Func(
        [],
        [CitizenCharterBackground],
        ['query'],
      ),
    'getCitizenCharterBackgroundImage' : IDL.Func(
        [IDL.Int],
        [IDL.Opt(ExternalBlob)],
        ['query'],
      ),
    'getCitizenCharterBackgroundImageById' : IDL.Func(
        [IDL.Int],
        [ExternalBlob],
        ['query'],
      ),
    'getCitizenCharterContactInfo' : IDL.Func(
        [],
        [CitizenCharterContactInfo],
        ['query'],
      ),
    'getCitizenCharterStaticImage' : IDL.Func(
        [],
        [CitizenCharterStaticImage],
        ['query'],
      ),
    'getCitizenCharterStaticImageById' : IDL.Func(
        [IDL.Int],
        [ExternalBlob],
        ['query'],
      ),
    'getCitizenCharterStaticImageByTimestamp' : IDL.Func(
        [IDL.Int],
        [IDL.Opt(ExternalBlob)],
        ['query'],
      ),
    'getClubOrganization' : IDL.Func([IDL.Nat], [ClubOrganization], ['query']),
    'getClubOrganizations' : IDL.Func(
        [],
        [IDL.Vec(ClubOrganization)],
        ['query'],
      ),
    'getContactInfoSection' : IDL.Func(
        [IDL.Nat],
        [ContactInfoSection],
        ['query'],
      ),
    'getCurrentBanner' : IDL.Func([], [BannerImage], ['query']),
    'getDepEdMission' : IDL.Func([], [DepEdMissionContent], ['query']),
    'getDepEdVision' : IDL.Func([], [DepEdVisionContent], ['query']),
    'getFileTypeBreakdown' : IDL.Func([], [FileTypeBreakdown], ['query']),
    'getFooterContactInfo' : IDL.Func([], [FooterContactInfo], ['query']),
    'getFooterSocialMedia' : IDL.Func([], [FooterSocialMedia], ['query']),
    'getHeritageSection' : IDL.Func([], [HeritageSectionContent], ['query']),
    'getHistoryBackgroundImage' : IDL.Func(
        [IDL.Int],
        [IDL.Opt(ExternalBlob)],
        ['query'],
      ),
    'getHistoryBackgroundImageById' : IDL.Func(
        [IDL.Int],
        [ExternalBlob],
        ['query'],
      ),
    'getLastActiveBanner' : IDL.Func([], [BannerImage], ['query']),
    'getLoginAnalytics' : IDL.Func([], [AnalyticsPeriod], ['query']),
    'getOfficeHoursSection' : IDL.Func(
        [IDL.Nat],
        [OfficeHoursSection],
        ['query'],
      ),
    'getOrganizationalStructure' : IDL.Func(
        [],
        [OrganizationalStructureContent],
        ['query'],
      ),
    'getRecentLoginRecords' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(LoginRecord)],
        ['query'],
      ),
    'getResourceSubcategory' : IDL.Func(
        [IDL.Text],
        [ResourceSubcategory],
        ['query'],
      ),
    'getSchoolHoursSection' : IDL.Func(
        [IDL.Nat],
        [SchoolHoursSection],
        ['query'],
      ),
    'getSliderImage' : IDL.Func([IDL.Nat], [SliderImage], ['query']),
    'getStorageStats' : IDL.Func([], [StorageStats], ['query']),
    'getTotalVisitors' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVisitorAnalytics' : IDL.Func([], [AnalyticsPeriod], ['query']),
    'initializeResources' : IDL.Func([], [], []),
    'initializeSuperAdmin' : IDL.Func([], [IDL.Principal], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'proxyPublicImage' : IDL.Func([IDL.Text, IDL.Vec(Header)], [IDL.Text], []),
    'recordLogin' : IDL.Func([], [], []),
    'recordVisitor' : IDL.Func([IDL.Text], [], []),
    'recoverSuperAdmin' : IDL.Func([], [IDL.Text], []),
    'removeBNHSHymn' : IDL.Func([], [], []),
    'removeCitizenCharterBackgroundImage' : IDL.Func([], [], []),
    'removeCitizenCharterStaticImage' : IDL.Func([], [], []),
    'removeHistoryBackgroundImage' : IDL.Func([], [], []),
    'removeOrganizationalChartBackground' : IDL.Func([], [], []),
    'removeOrganizationalStructureStaticImage' : IDL.Func([], [], []),
    'removeOrganizationalStructureTitleBackground' : IDL.Func([], [], []),
    'reorderSliderImages' : IDL.Func([IDL.Vec(IDL.Nat)], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setAdminUserStatus' : IDL.Func([IDL.Principal, IDL.Bool], [], []),
    'setBNHSHymn' : IDL.Func([ExternalBlob], [], []),
    'setCitizenCharterBackgroundImage' : IDL.Func([ExternalBlob], [], []),
    'setCitizenCharterStaticImage' : IDL.Func([ExternalBlob], [], []),
    'setHistoryBackgroundImage' : IDL.Func([ExternalBlob], [], []),
    'setOrganizationalChartBackground' : IDL.Func([ExternalBlob], [], []),
    'setOrganizationalStructureStaticImage' : IDL.Func([ExternalBlob], [], []),
    'setOrganizationalStructureTitleBackground' : IDL.Func(
        [ExternalBlob],
        [],
        [],
      ),
    'swapSliderImages' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateAdminUserPermissions' : IDL.Func(
        [IDL.Principal, IDL.Vec(AdminPermission)],
        [],
        [],
      ),
    'updateAlumniContent' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateAlumniProfile' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateBannerImage' : IDL.Func(
        [IDL.Nat, BannerImageSource, IDL.Text, IDL.Text],
        [BannerImage],
        [],
      ),
    'updateCitizenCharterContactInfo' : IDL.Func([], [], []),
    'updateClubOrganization' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    'updateContactInfoSection' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateDepEdMission' : IDL.Func([IDL.Nat], [], []),
    'updateDepEdVision' : IDL.Func([IDL.Nat], [], []),
    'updateFooterContactInfo' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateFooterSocialMedia' : IDL.Func([IDL.Text], [], []),
    'updateHeritageSection' : IDL.Func([IDL.Text, FormattedText], [], []),
    'updateOfficeHoursSection' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateSchoolHoursSection' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateSliderImage' : IDL.Func(
        [IDL.Nat, SliderImageSource, IDL.Text, IDL.Text, IDL.Nat],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };