/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AdminPermission = { 'ManageResources' : null } |
  { 'ManageAlumni' : null } |
  { 'ManageSlider' : null } |
  { 'ManageCitizenCharter' : null } |
  { 'ManageHeritage' : null } |
  { 'ManageHymn' : null } |
  { 'ManageBanners' : null } |
  { 'ManageFooter' : null } |
  { 'ManageClubs' : null };
export interface AdminUserData {
  'permissions' : Array<AdminPermission>,
  'principal' : Principal,
  'name' : string,
  'createdAt' : bigint,
  'isActive' : boolean,
  'email' : string,
  'lastLogin' : [] | [bigint],
}
export interface AlumniContent {
  'title' : string,
  'lastUpdated' : bigint,
  'description' : string,
  'communityEngagement' : string,
}
export interface AlumniProfile {
  'id' : bigint,
  'name' : string,
  'graduationYear' : string,
  'achievements' : string,
  'currentPosition' : string,
}
export interface AnalyticsPeriod {
  'monthly' : bigint,
  'yearly' : bigint,
  'daily' : bigint,
  'weekly' : bigint,
}
export interface BNHSHymnContent {
  'video' : ExternalBlob,
  'lastUpdated' : bigint,
}
export interface BannerFileMetadata {
  'id' : bigint,
  'isAnimated' : boolean,
  'file' : ExternalBlob,
}
export interface BannerImage {
  'id' : bigint,
  'title' : string,
  'description' : string,
  'isActive' : boolean,
  'timestamp' : bigint,
  'image' : BannerImageSource,
}
export type BannerImageSource = { 'url' : string } |
  { 'file' : BannerFileMetadata };
export interface CitizenCharterBackground {
  'lastUpdated' : bigint,
  'isActive' : boolean,
  'backgroundImage' : [] | [ExternalBlob],
}
export interface CitizenCharterContactInfo {
  'title' : string,
  'contactInfo' : string,
  'officeHours' : string,
  'lastUpdated' : bigint,
  'schoolAddress' : string,
  'schoolHours' : string,
}
export interface CitizenCharterStaticImage {
  'lastUpdated' : bigint,
  'staticImage' : [] | [ExternalBlob],
}
export interface ClubOrganization {
  'id' : bigint,
  'members' : Array<string>,
  'name' : string,
  'activities' : Array<string>,
  'description' : string,
}
export interface ContactInfoSection {
  'id' : bigint,
  'content' : string,
  'createdAt' : bigint,
  'isActive' : boolean,
  'updatedAt' : bigint,
}
export interface DepEdMissionContent {
  'mission' : string,
  'lastUpdated' : bigint,
  'version' : bigint,
}
export interface DepEdVisionContent {
  'mission' : string,
  'coreValues' : string,
  'lastUpdated' : bigint,
  'version' : bigint,
  'bnhsStatisticalBulletinTitle' : string,
  'mandates' : string,
  'vision' : string,
}
export type ExternalBlob = Uint8Array;
export interface FileTypeBreakdown {
  'documents' : bigint,
  'videos' : bigint,
  'images' : bigint,
}
export type FontStyle = { 'italic' : null } |
  { 'normal' : null } |
  { 'bold' : null } |
  { 'underline' : null };
export interface FooterContactInfo {
  'lastUpdated' : bigint,
  'email' : string,
  'schoolAddress' : string,
  'phone' : string,
}
export interface FooterSocialMedia {
  'lastUpdated' : bigint,
  'facebookUrl' : string,
}
export interface FormattedText {
  'content' : string,
  'fontStyle' : FontStyle,
  'fontSize' : number,
  'alignment' : TextAlignment,
}
export interface Header { 'value' : string, 'name' : string }
export interface HeritageSectionContent {
  'title' : string,
  'lastUpdated' : bigint,
  'formattedText' : FormattedText,
  'backgroundImage' : [] | [ExternalBlob],
  'orgChartBackground' : [] | [ExternalBlob],
}
export interface LoginRecord {
  'principal' : Principal,
  'role' : string,
  'timestamp' : bigint,
}
export interface OfficeHoursSection {
  'id' : bigint,
  'content' : string,
  'createdAt' : bigint,
  'isActive' : boolean,
  'updatedAt' : bigint,
}
export interface OrganizationalStructureContent {
  'lastUpdated' : bigint,
  'titleBackground' : [] | [ExternalBlob],
  'staticImage' : [] | [ExternalBlob],
}
export interface ResourceSubcategory {
  'url' : string,
  'title' : string,
  'isExternal' : boolean,
}
export interface SchoolHoursSection {
  'id' : bigint,
  'content' : string,
  'createdAt' : bigint,
  'isActive' : boolean,
  'updatedAt' : bigint,
}
export interface SliderImage {
  'id' : bigint,
  'title' : string,
  'displayOrder' : bigint,
  'description' : string,
  'timestamp' : bigint,
  'image' : SliderImageSource,
}
export type SliderImageSource = { 'url' : string } |
  { 'file' : BannerFileMetadata };
export interface StorageStats {
  'fileCount' : bigint,
  'lastUpdated' : bigint,
  'usedSpace' : bigint,
  'availableSpace' : bigint,
  'totalCapacity' : bigint,
}
export type TextAlignment = { 'center' : null } |
  { 'left' : null } |
  { 'justify' : null } |
  { 'right' : null };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'name' : string,
  'role' : string,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'activateBanner' : ActorMethod<[bigint], undefined>,
  'addBannerImage' : ActorMethod<
    [BannerImageSource, string, string],
    BannerImage
  >,
  'addSliderImage' : ActorMethod<[SliderImageSource, string, string], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAdminUser' : ActorMethod<
    [Principal, string, string, Array<AdminPermission>],
    undefined
  >,
  'createAlumniProfile' : ActorMethod<
    [string, string, string, string],
    undefined
  >,
  'createClubOrganization' : ActorMethod<
    [string, string, Array<string>, Array<string>],
    undefined
  >,
  'createContactInfoSection' : ActorMethod<[string], bigint>,
  'createOfficeHoursSection' : ActorMethod<[string], bigint>,
  'createSchoolHoursSection' : ActorMethod<[string], bigint>,
  'deactivateBanner' : ActorMethod<[bigint], undefined>,
  'deleteAdminUser' : ActorMethod<[Principal], undefined>,
  'deleteAlumniProfile' : ActorMethod<[bigint], undefined>,
  'deleteBanner' : ActorMethod<[bigint], undefined>,
  'deleteClubOrganization' : ActorMethod<[bigint], undefined>,
  'deleteContactInfoSection' : ActorMethod<[bigint], undefined>,
  'deleteOfficeHoursSection' : ActorMethod<[bigint], undefined>,
  'deleteSchoolHoursSection' : ActorMethod<[bigint], undefined>,
  'deleteSliderImage' : ActorMethod<[bigint], undefined>,
  'getActiveBanners' : ActorMethod<[], Array<BannerImage>>,
  'getAdminUser' : ActorMethod<[Principal], AdminUserData>,
  'getAllAdminUsers' : ActorMethod<[], Array<AdminUserData>>,
  'getAllAlumniProfiles' : ActorMethod<[], Array<AlumniProfile>>,
  'getAllBanners' : ActorMethod<[], Array<BannerImage>>,
  'getAllContactInfoSections' : ActorMethod<[], Array<ContactInfoSection>>,
  'getAllOfficeHoursSections' : ActorMethod<[], Array<OfficeHoursSection>>,
  'getAllResourceSubcategories' : ActorMethod<[], Array<ResourceSubcategory>>,
  'getAllSchoolHoursSections' : ActorMethod<[], Array<SchoolHoursSection>>,
  'getAllSliderImages' : ActorMethod<[], Array<SliderImage>>,
  'getAlumniContent' : ActorMethod<[], AlumniContent>,
  'getAlumniProfile' : ActorMethod<[bigint], AlumniProfile>,
  'getBNHSHymnMetadata' : ActorMethod<[], BNHSHymnContent>,
  'getBNHSHymnVideo' : ActorMethod<[], ExternalBlob>,
  'getBannerById' : ActorMethod<[bigint], BannerImage>,
  'getBannerVersion' : ActorMethod<[], bigint>,
  'getCallerPermissions' : ActorMethod<[], Array<AdminPermission>>,
  'getCallerRole' : ActorMethod<[], string>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCitizenCharterBackground' : ActorMethod<[], CitizenCharterBackground>,
  'getCitizenCharterBackgroundImage' : ActorMethod<
    [bigint],
    [] | [ExternalBlob]
  >,
  'getCitizenCharterBackgroundImageById' : ActorMethod<[bigint], ExternalBlob>,
  'getCitizenCharterContactInfo' : ActorMethod<[], CitizenCharterContactInfo>,
  'getCitizenCharterStaticImage' : ActorMethod<[], CitizenCharterStaticImage>,
  'getCitizenCharterStaticImageById' : ActorMethod<[bigint], ExternalBlob>,
  'getCitizenCharterStaticImageByTimestamp' : ActorMethod<
    [bigint],
    [] | [ExternalBlob]
  >,
  'getClubOrganization' : ActorMethod<[bigint], ClubOrganization>,
  'getClubOrganizations' : ActorMethod<[], Array<ClubOrganization>>,
  'getContactInfoSection' : ActorMethod<[bigint], ContactInfoSection>,
  'getCurrentBanner' : ActorMethod<[], BannerImage>,
  'getDepEdMission' : ActorMethod<[], DepEdMissionContent>,
  'getDepEdVision' : ActorMethod<[], DepEdVisionContent>,
  'getFileTypeBreakdown' : ActorMethod<[], FileTypeBreakdown>,
  'getFooterContactInfo' : ActorMethod<[], FooterContactInfo>,
  'getFooterSocialMedia' : ActorMethod<[], FooterSocialMedia>,
  'getHeritageSection' : ActorMethod<[], HeritageSectionContent>,
  'getHistoryBackgroundImage' : ActorMethod<[bigint], [] | [ExternalBlob]>,
  'getHistoryBackgroundImageById' : ActorMethod<[bigint], ExternalBlob>,
  'getLastActiveBanner' : ActorMethod<[], BannerImage>,
  'getLoginAnalytics' : ActorMethod<[], AnalyticsPeriod>,
  'getOfficeHoursSection' : ActorMethod<[bigint], OfficeHoursSection>,
  'getOrganizationalStructure' : ActorMethod<
    [],
    OrganizationalStructureContent
  >,
  'getRecentLoginRecords' : ActorMethod<[bigint], Array<LoginRecord>>,
  'getResourceSubcategory' : ActorMethod<[string], ResourceSubcategory>,
  'getSchoolHoursSection' : ActorMethod<[bigint], SchoolHoursSection>,
  'getSliderImage' : ActorMethod<[bigint], SliderImage>,
  'getStorageStats' : ActorMethod<[], StorageStats>,
  'getTotalVisitors' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVisitorAnalytics' : ActorMethod<[], AnalyticsPeriod>,
  'initializeResources' : ActorMethod<[], undefined>,
  'initializeSuperAdmin' : ActorMethod<[], Principal>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'proxyPublicImage' : ActorMethod<[string, Array<Header>], string>,
  'recordLogin' : ActorMethod<[], undefined>,
  'recordVisitor' : ActorMethod<[string], undefined>,
  'recoverSuperAdmin' : ActorMethod<[], string>,
  'removeBNHSHymn' : ActorMethod<[], undefined>,
  'removeCitizenCharterBackgroundImage' : ActorMethod<[], undefined>,
  'removeCitizenCharterStaticImage' : ActorMethod<[], undefined>,
  'removeHistoryBackgroundImage' : ActorMethod<[], undefined>,
  'removeOrganizationalChartBackground' : ActorMethod<[], undefined>,
  'removeOrganizationalStructureStaticImage' : ActorMethod<[], undefined>,
  'removeOrganizationalStructureTitleBackground' : ActorMethod<[], undefined>,
  'reorderSliderImages' : ActorMethod<[Array<bigint>], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setAdminUserStatus' : ActorMethod<[Principal, boolean], undefined>,
  'setBNHSHymn' : ActorMethod<[ExternalBlob], undefined>,
  'setCitizenCharterBackgroundImage' : ActorMethod<[ExternalBlob], undefined>,
  'setCitizenCharterStaticImage' : ActorMethod<[ExternalBlob], undefined>,
  'setHistoryBackgroundImage' : ActorMethod<[ExternalBlob], undefined>,
  'setOrganizationalChartBackground' : ActorMethod<[ExternalBlob], undefined>,
  'setOrganizationalStructureStaticImage' : ActorMethod<
    [ExternalBlob],
    undefined
  >,
  'setOrganizationalStructureTitleBackground' : ActorMethod<
    [ExternalBlob],
    undefined
  >,
  'swapSliderImages' : ActorMethod<[bigint, bigint], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateAdminUserPermissions' : ActorMethod<
    [Principal, Array<AdminPermission>],
    undefined
  >,
  'updateAlumniContent' : ActorMethod<[string, string, string], undefined>,
  'updateAlumniProfile' : ActorMethod<
    [bigint, string, string, string, string],
    undefined
  >,
  'updateBannerImage' : ActorMethod<
    [bigint, BannerImageSource, string, string],
    BannerImage
  >,
  'updateCitizenCharterContactInfo' : ActorMethod<[], undefined>,
  'updateClubOrganization' : ActorMethod<
    [bigint, string, string, Array<string>, Array<string>],
    undefined
  >,
  'updateContactInfoSection' : ActorMethod<[bigint, string], undefined>,
  'updateDepEdMission' : ActorMethod<[bigint], undefined>,
  'updateDepEdVision' : ActorMethod<[bigint], undefined>,
  'updateFooterContactInfo' : ActorMethod<[string, string, string], undefined>,
  'updateFooterSocialMedia' : ActorMethod<[string], undefined>,
  'updateHeritageSection' : ActorMethod<[string, FormattedText], undefined>,
  'updateOfficeHoursSection' : ActorMethod<[bigint, string], undefined>,
  'updateSchoolHoursSection' : ActorMethod<[bigint, string], undefined>,
  'updateSliderImage' : ActorMethod<
    [bigint, SliderImageSource, string, string, bigint],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];